name: Build and deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      
      - name: Download wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: latest

      - name: Install and build
        run: |
          mkdir -p docs
          rm -rf ./docs/*
          wasm-pack build
          cd www
          npm install
          npm run build
          cp ./styles/*.css ./dist
          cp -r ./images ./dist
          mv ./dist/* ../docs
          cd ../
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          single-commit: true
